quarkus.oidc.auth-server-url=http://localhost:8081/realms/inventory-realm
quarkus.oidc.client-id=inventory-service
quarkus.oidc.credentials.secret=zwaDJaHiuw5udO6w0oBI1stCEVVLOSVA
quarkus.oidc.application-type=service

quarkus.http.auth.permission.authenticated.paths=/products,/products/*
quarkus.http.auth.permission.authenticated.policy=authenticated

quarkus.http.auth.permission.admin.paths=/admin/*
quarkus.http.auth.permission.admin.policy=admin-policy
quarkus.http.auth.policy.admin-policy.roles-allowed=admin
